//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaleriKategori
    {
        public int GaleriKategoriID { get; set; }
        public string GKAd { get; set; }
        public int GaleriID { get; set; }
    
        public virtual Galeri Galeri { get; set; }
    }
}
