//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoTripDB2Entities : DbContext
    {
        public GoTripDB2Entities()
            : base("name=GoTripDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<BlogKategori> BlogKategori { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<GaleriKategori> GaleriKategori { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Kurumsal> Kurumsal { get; set; }
        public virtual DbSet<TurPaket> TurPaket { get; set; }
    }
}
