//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurPaket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TurPaket()
        {
            this.Kurumsal = new HashSet<Kurumsal>();
        }
    
        public int TurPaketID { get; set; }
        public string TPAd { get; set; }
        public int TPFiyat { get; set; }
        public int TPSure { get; set; }
        public string TPKonum { get; set; }
        public string TPDetay { get; set; }
        public string TPResim { get; set; }
        public int BlogKategoriID { get; set; }
    
        public virtual BlogKategori BlogKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurumsal> Kurumsal { get; set; }
    }
}
